### ISSUE TITLE
tailwindui.com is Selling this open source Project For $99

### ISSUE THREAD

**Issue by S4tyendra** [mirsazzathossain/mirsazzathossain.me#163]
This issue is to let you know that tailwindui.com is just edited some stuff in this repo and selling in their site.
ws link: https://tailwindui.com/templates/spotlight
preview link: https://spotlight.tailwindui.com/

This is why developers doesn't prefer to create open source projects.

**Comment by mirsazzathossain** [comment]
Hi @S4tyendra,
Thank you for bringing up this concern. I understand that there might be some confusion regarding the similarities between my project and the one being sold on **tailwindui.com**. However, I would like to clarify that my project was actually inspired by the **spotlight theme**, not the other way around. This information is clearly mentioned in the **README** file of my repository.

As an open-source project, I believe in transparency and giving credit where it's due. I acknowledge the existence of the **spotlight** theme and its influence on my work. My intention was to create a similar experience and provide it as a free resource for the community.

I apologize if there was any misunderstanding, but I assure you that my project is not a copy or an edited version of the one being sold on **tailwindui.com**. It is an **independent effort** created to share and contribute to the open-source community.

If you have any further questions or concerns, please feel free to let me know. I'm more than happy to address them.
